[tox]
envlist =
    py38
    py39
    py310
    py311
    py312
    py313
    py314
    py315

[pytest]
norecursedirs = docs dist
filterwarnings =
    error::DeprecationWarning
    error::PendingDeprecationWarning

[testenv]
passenv = USERNAME
setenv =
    COVERAGE_FILE = {env_tmp_dir}/.coverage
extras = test
commands =
    pytest --cov logging_ {posargs}
